package mapeo;
// Generated 2/06/2016 12:32:34 AM by Hibernate Tools 4.3.1



/**
 * CalificacionId generated by hbm2java
 */
public class CalificacionId  implements java.io.Serializable {


     private int idUsuarioCalificado;
     private int idUsuarioCalifica;
     private int idCompra;

    public CalificacionId() {
    }

    public CalificacionId(int idUsuarioCalificado, int idUsuarioCalifica, int idCompra) {
       this.idUsuarioCalificado = idUsuarioCalificado;
       this.idUsuarioCalifica = idUsuarioCalifica;
       this.idCompra = idCompra;
    }
   
    public int getIdUsuarioCalificado() {
        return this.idUsuarioCalificado;
    }
    
    public void setIdUsuarioCalificado(int idUsuarioCalificado) {
        this.idUsuarioCalificado = idUsuarioCalificado;
    }
    public int getIdUsuarioCalifica() {
        return this.idUsuarioCalifica;
    }
    
    public void setIdUsuarioCalifica(int idUsuarioCalifica) {
        this.idUsuarioCalifica = idUsuarioCalifica;
    }
    public int getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(int idCompra) {
        this.idCompra = idCompra;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CalificacionId) ) return false;
		 CalificacionId castOther = ( CalificacionId ) other; 
         
		 return (this.getIdUsuarioCalificado()==castOther.getIdUsuarioCalificado())
 && (this.getIdUsuarioCalifica()==castOther.getIdUsuarioCalifica())
 && (this.getIdCompra()==castOther.getIdCompra());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdUsuarioCalificado();
         result = 37 * result + this.getIdUsuarioCalifica();
         result = 37 * result + this.getIdCompra();
         return result;
   }   


}


