package mapeo;
// Generated 13/04/2016 01:37:52 PM by Hibernate Tools 4.3.1



/**
 * DatosUsuario generated by hbm2java
 */
public class DatosUsuario  implements java.io.Serializable {


     private int idDatosUsuario;
     private int nombreUsuario;
     private String email;
     private int direccion;
     private byte[] imagenUsuario;
     private String telefono;
     private int edad;

    public DatosUsuario() {
    }

    public DatosUsuario(int idDatosUsuario, int nombreUsuario, String email, int direccion, byte[] imagenUsuario, String telefono, int edad) {
       this.idDatosUsuario = idDatosUsuario;
       this.nombreUsuario = nombreUsuario;
       this.email = email;
       this.direccion = direccion;
       this.imagenUsuario = imagenUsuario;
       this.telefono = telefono;
       this.edad = edad;
    }
   
    public int getIdDatosUsuario() {
        return this.idDatosUsuario;
    }
    
    public void setIdDatosUsuario(int idDatosUsuario) {
        this.idDatosUsuario = idDatosUsuario;
    }
    public int getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(int nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(int direccion) {
        this.direccion = direccion;
    }
    public byte[] getImagenUsuario() {
        return this.imagenUsuario;
    }
    
    public void setImagenUsuario(byte[] imagenUsuario) {
        this.imagenUsuario = imagenUsuario;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }




}


