package mapeo;
// Generated 13/04/2016 01:37:52 PM by Hibernate Tools 4.3.1



/**
 * GaleriaPublicacion generated by hbm2java
 */
public class GaleriaPublicacion  implements java.io.Serializable {


     private int idGaleria;
     private byte[] urlImagen;
     private String textoImagen;

    public GaleriaPublicacion() {
    }

	
    public GaleriaPublicacion(int idGaleria, byte[] urlImagen) {
        this.idGaleria = idGaleria;
        this.urlImagen = urlImagen;
    }
    public GaleriaPublicacion(int idGaleria, byte[] urlImagen, String textoImagen) {
       this.idGaleria = idGaleria;
       this.urlImagen = urlImagen;
       this.textoImagen = textoImagen;
    }
   
    public int getIdGaleria() {
        return this.idGaleria;
    }
    
    public void setIdGaleria(int idGaleria) {
        this.idGaleria = idGaleria;
    }
    public byte[] getUrlImagen() {
        return this.urlImagen;
    }
    
    public void setUrlImagen(byte[] urlImagen) {
        this.urlImagen = urlImagen;
    }
    public String getTextoImagen() {
        return this.textoImagen;
    }
    
    public void setTextoImagen(String textoImagen) {
        this.textoImagen = textoImagen;
    }




}


