package mapeo;
// Generated 13/04/2016 01:37:52 PM by Hibernate Tools 4.3.1



/**
 * NombreUsuario generated by hbm2java
 */
public class NombreUsuario  implements java.io.Serializable {


     private int idNombreUsuario;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;

    public NombreUsuario() {
    }

    public NombreUsuario(int idNombreUsuario, String nombre, String apellidoPaterno, String apellidoMaterno) {
       this.idNombreUsuario = idNombreUsuario;
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
    }
   
    public int getIdNombreUsuario() {
        return this.idNombreUsuario;
    }
    
    public void setIdNombreUsuario(int idNombreUsuario) {
        this.idNombreUsuario = idNombreUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }




}


