package mapeo;
// Generated 13/04/2016 01:37:52 PM by Hibernate Tools 4.3.1



/**
 * Publicacion generated by hbm2java
 */
public class Publicacion  implements java.io.Serializable {


     private int idPublicacion;
     private String descripcion;
     private int imagenes;
     private int precioInical;
     private int precioFinal;
     private int precioActual;

    public Publicacion() {
    }

    public Publicacion(int idPublicacion, String descripcion, int imagenes, int precioInical, int precioFinal, int precioActual) {
       this.idPublicacion = idPublicacion;
       this.descripcion = descripcion;
       this.imagenes = imagenes;
       this.precioInical = precioInical;
       this.precioFinal = precioFinal;
       this.precioActual = precioActual;
    }
   
    public int getIdPublicacion() {
        return this.idPublicacion;
    }
    
    public void setIdPublicacion(int idPublicacion) {
        this.idPublicacion = idPublicacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getImagenes() {
        return this.imagenes;
    }
    
    public void setImagenes(int imagenes) {
        this.imagenes = imagenes;
    }
    public int getPrecioInical() {
        return this.precioInical;
    }
    
    public void setPrecioInical(int precioInical) {
        this.precioInical = precioInical;
    }
    public int getPrecioFinal() {
        return this.precioFinal;
    }
    
    public void setPrecioFinal(int precioFinal) {
        this.precioFinal = precioFinal;
    }
    public int getPrecioActual() {
        return this.precioActual;
    }
    
    public void setPrecioActual(int precioActual) {
        this.precioActual = precioActual;
    }




}


